<?php 
function tpl_1_1_85eafe32acd1130ae7ed3c4db43c6fb9d( $tpl, $ctx ) {
/* Generated by PHPTAL from /home/john/eclipse/Simplicity PHP/app/resources/views/other/view.html */ ;
ob_start() ;
$glb = $tpl->getGlobalContext() ;
$ctx->setXmlDeclaration('<?xml version="1.0"?>') ;
?>
<html>
  <head>
    <title>
      place for the page title
    </title>
  </head>
  <body>
    <h1><?php echo phptal_escape($ctx->title, ENT_QUOTES, 'UTF-8') ?></h1>
  </body>
</html><?php 
$_result_ = ob_get_contents() ;
ob_end_clean() ;
return $_result_ ;

}

?>